### ISSUE TITLE
Missing social icons? 

### ISSUE THREAD

**Issue by sethgrid** [funkydan2/hugo-kiera#20]
Thanks for maintaining this theme. How do I get the social icons to show up?
I might have a basic misunderstanding, but I don't see the social icons showing up on my page. 

My live config:
https://github.com/sethgrid/me/blob/master/site/config.toml
My live site:
sethammons.com

**Comment by funkydan2** [comment]
I cloned your site and ran `hugo server` and the social icons show up on the test server.

When I look at your live site with the Firefox development tools I saw the problem - your site is being served as https, so change the top line of your config file to read `baseURL = "https://sethammons.com/"`

The reason this is breaking is because hugo hardcodes the `baseURL` value into your site's html - so it's referencing `http://sethammons.com/fontawesome/css/all.min.css` and most modern browsers won't allow a site served over HTTPS to also grab insecure content.

**Comment by mkrump** [comment]
I just moved from https://github.com/avianto/hugo-kiera and i'm having a similar issue (no longer see social icons). 

My config:
https://github.com/mkrump/blog/blob/master/config.toml
My site:
https://matthewkrump.com/

**Comment by funkydan2** [comment]
Hi @mkrump,

The issue isn't with the theme (as such). However, due to a change in how the theme works, your customised partial no longer works. The theme uses a data file for social icons, which allows users more flexibility. Also, we're now serving fontawesome locally rather than using their fontkit.

You'll need to change https://github.com/mkrump/blog/blob/master/layouts/partials/header.html

There's two ways you can fix it.

1. Just copy the section of  https://github.com/funkydan2/hugo-kiera/blob/master/layouts/partials/header.html where the site ranges through a data file to match social networks and icons.
2. Change the code which creates the icons so that it reads `<i class="fab fa-linkedin fa-lg` (rather than `class="fa`

**Comment by mkrump** [comment]
Ah. I missed that had changed. Just copying over / adapting the partial from theme fixed it. Thanks again!
