### ISSUE TITLE
Remove 'subscribe' link from footer

### ISSUE THREAD

**Issue by sethgrid** [funkydan2/hugo-kiera#21]
I don't see a way to remove the 'subscribe' link from the footer. Is that an option that can be added?

**Comment by funkydan2** [comment]
The easy way for you to remove the subscribe link on your site is to override the `footer.html` partial.

To do this, make a copy the file `./themes/hugo-kiera/layouts/partials/footer.html` and put the copy in `/layouts/partials/footer.html`. Then delete line 5.

The way hugo works is that it'll now use *your* version of the `footer.html` partial to build pages rather than the theme's.
----
I could look into having a variable to turn on/off the subscribe link...though I'm keen to keep the configuration as simple as possible and I'm not sure how popular this feature would be. But I'll leave the issue open and we'll see if there are more requests for the feature.

**Comment by sethgrid** [comment]
I really appreciate the education on this. Thanks! And thanks on the other issue too. Y'all are awesome.

**Comment by niaahmaa** [comment]
in Line 5: <a href="{{.Site.BaseURL}}index.xml">{{ T "subscribe" }} </a></h6>

Changing "subscribe" to any other characters (EG: "Unsubscribe") will result in the link to disappear from view, is that normal?

**Comment by funkydan2** [comment]
@niaahmaa yes, that is expected behaviour. The `T` function is for translations and so it will only work with strings defined in [the i18n toml files](https://github.com/funkydan2/hugo-kiera/blob/master/i18n/en.toml). 

(I actually can't find this function documented anywhere, maybe we should be using the [i18n function](https://gohugo.io/content-management/multilingual/#translation-of-strings)...but it's working at the moment, so I'm happy with that.)
