### ISSUE TITLE
List of issues (Kiera version)

### ISSUE THREAD

**Issue by niaahmaa** [funkydan2/hugo-kiera#27]
Hello funkydan2, this was originally posted on [avianto's hugo-kiera's page](https://github.com/avianto/hugo-kiera/issues/37). I had the same issue installing the theme from your fork.

1. 'Tags' link from the toolbar works as normal when accessed from the homepage. However, if I were to click on the 'Tags' link from anywhere else other than the homepage, it fails. The problem was resulted from adding a new line to the original URL. (EG: http://website/tags/ >> http://website/tags/tags/ >> http://website/tags/tags/tags/). 

This problem does not seem to affect the 'About Hugo' and 'Posts' link, only the ones added directly through the function [[menu.main]] in 'config.toml'. 

2. Posts created from ‘Create Post’ addin in Rstudio is saved in a different folder (“Post” folder instead of “Posts” folder). The ‘Posts’ link on the homepage directs you to the “Posts” folder, meaning every post you created from the ‘Create Post’ function cannot be viewed normally unless accessed through ‘Tags’ or ‘Categories’. 

This can be solved by moving all files from the 'Post' folder to 'Posts' folder, but there has to be a better way to do this. 

Also, is it possible to remove or rename the default links from the toolbar (EG: 'About Hugo' to 'About Something Else')?

**Comment by funkydan2** [comment]
I'll come back to question 1 when I've got more time, but for question 2 it's just a matter of configuring the menu.

Have a look at https://gohugo.io/content-management/menus/#add-content-to-menus

You can either add entries to the menu through a page's frontmatter or through the site config file. If you look at the code for the exampleSite, you can see examples of both (though the config file option is commented out in the example).

As for putting content in a `post` directory rather than `posts`, either create the relevant menu entry in your config file or in the `_index.md` file in the `/content/post` directory.

(If you're still having difficulties with configuring the menu, can you start a thread on the [hugo forums](https://discourse.gohugo.io). The issue you're having isn't with this theme, but rather learning how hugo works.)

**Comment by funkydan2** [comment]
For (1) - can you have look at the [update config file in the exampleSite](https://github.com/funkydan2/hugo-kiera/blob/master/exampleSite/config.toml) - lines 36 and 43. I think if you set `url = "tags` then your porblem shows up, but if you have a leading forward slash `url = "/tags"` then it works as expected.

**Comment by funkydan2** [comment]
And [this commit](https://github.com/funkydan2/hugo-kiera/commit/2f9dfa120498f688baccc4dde34c1cbd2a8b0f0d) should also make the menus more robust. Please update your theme and let me know.

**Comment by niaahmaa** [comment]
> For (1) - can you have look at the [update config file in the exampleSite](https://github.com/funkydan2/hugo-kiera/blob/master/exampleSite/config.toml) - lines 36 and 43. I think if you set `url = "tags` then your porblem shows up, but if you have a leading forward slash `url = "/tags"` then it works as expected.

> As for putting content in a post directory rather than posts, either create the relevant menu entry in your config file or in the _index.md file in the /content/post directory.

Thank you, this fixed the problem.
