### ISSUE TITLE
OpenGraph?

### ISSUE THREAD

**Issue by jsumners** [funkydan2/hugo-kiera#5]
https://gohugo.io/templates/internal/#open-graph

It'd be nice if the header template could include a reference to the opengraph built-in. Maybe via a preference?

**Comment by funkydan2** [comment]
Good idea, however, we need to think a little about the implementation.

The open graph metadata itself is really easy to do. I just need to put a line or two in `/partials/header_includes.html`, and then writers need to add an **array** of images to pages front matter, and Hugo will look after the rest.

The question I've got is how (or if) to display the *feature image* on the page. I reckon most people would expect that if they put `images = ["feature_image.jpg"]` in the front matter, that image would be displayed somewhere on the page. But this theme is, by design, simple and wasn't built with a feature image in mind.

So my question is, how do you think a feature image should be displayed? (Think about [this page on the demo site](https://themes.gohugo.io//theme/hugo-kiera/post/markdown-syntax/).) I've got two ideas:
1. Full width (default height) below the metadata
2. *Half* width beside the metadata.
Option (2) might be quite nice, simple, not too distracting, but I'd need to dig into the CSS to see what is available for multi-column layouts.

**Comment by jsumners** [comment]
🤔

I didn’t catch the required image part. For me, I’d like to keep it simple. I’d like to define a single image in the theme TOML and have it apply to all pages. It wouldn’t have to show up in any page, just used to make the social media links more attractive.

**Comment by funkydan2** [comment]
Do you know what - you're right! That's really easy to do.

**Comment by jsumners** [comment]
Awesome. Thank you very much. And thank you for keeping the theme updated.
