### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by AlekSi** [funkydan2/hugo-kiera#8]
There are 70 commits to master since last tag.

**Comment by funkydan2** [comment]
Thanks for the suggestion @AlekSi.

What fixes/improvements do you think warrant a new release being tagged? 

Since hugo recommends [using submodules for themes](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme),

**Comment by funkydan2** [comment]
(Sorry, clicked the wrong button.)

**Comment by funkydan2** [comment]
Thanks for the suggestion.

Since the hugo docs [recommend using submodules for themes](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme) I haven't been considering 'releasing' a zipped up version of the theme, but rather consider it a 'rolling release'.

However, if you reckon this would be helpful, I'm to discuss it further. What do you think would trigger a new release?

**Comment by AlekSi** [comment]
I do use submodules for themes. But checking out the tagged revision makes it easier to reason about it than checking out some random-looking commit hash or follow the master branch. Changelogs are useful; commit logs – not so much.

**Comment by funkydan2** [comment]
This is a new feature of github for me.

I've made a small change to the theme and I think I've *tagged* this release.

If I understand correctly, this feature can (should?) replace updating CHANGELOG.md.
